### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [wrenngreg/prj-rev-bwfs-dasmoto#4]
Your project was well structured and written as it shows through the visual side of your project.

Just remember that the pathing you used in your index.html file to reference the stylesheet does not work for others; and only yourself.
Because we do not have access to "C:\Users\wrenn\OneDrive\Documents" (only you do), we aren't able to call the stylesheet which throws the whole look of your project off. If you were to just put ".\Resources\style.css" instead, it should work as desired.
The different here is absolute and relative pathing, please do look it up and ensure that your next project will have it correctly!

Other than that, great job on this project!
Grade: Meets expectation. Keep up the good work!

**Comment by wrenngreg** [comment]
Thanks for the feedback!
